behaviors:
  CylinderThing:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 256
      learning_rate: 0.001
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000
    time_horizon: 256
    summary_freq: 1000